name: Continuous integration (PRs)
on: pull_request
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm ci
      - name: Run ViTest tests
        run: npm run test
      - run: npm run build
      - run: npm run check
