name: Automated release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Automated release
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Generate files
        run: node src/scripts/build.js
      - name: Run ViTest tests
        run: npm run test
      - run: npm run check
      - name: Build the package
        run: npm run package
      - run: >
          npx
          -p "@semantic-release/commit-analyzer"
          -p "@semantic-release/release-notes-generator"
          -p conventional-changelog-conventionalcommits
          -p "@semantic-release/exec"
          -p semantic-release
          -- semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}